version: '3'

services:
  db:
    image : moonkh/moon:1.0
    container_name: moonkh_DeepFake_0
    volumes : 
    - .:/workspace
    - virtual_datapath:real_data_path
    shm_size: 20gb # you can change size depend on your resources.
    command: tail -f /dev/null
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"] # device id : 0, 1, ...
              capabilities: [gpu]